[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Piano Improvisation Course"
  pageRef = "/courses/piano-improvisation"
  weight = 20

[[main]]
  name = "MIDI Course"
  pageRef = "/courses/midi"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "/posts"
  weight = 40